name: Automated Releases

on:
  workflow_dispatch:

jobs:
  changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: TriPSs/conventional-changelog-action@latest
        name: conventional Changelog Action
        id: changelog
        with:
          github-token: ${{ github.token }}
      - uses: actions/github-script@v7
        env:
          GH_TOKEN: ${{ github.token }}
        with:
          github-token: ${{ github.token }}
          script: |
            const { owner, repo } = context.repo
            await exec.exec('gh', ['release', 'delete', 'latest']).catch((e) => console.log)
            await exec.exec('git', ['tag', '-d', 'latest']).catch((e) => console.log)
      - uses: actions/create-release@latest
        name: create release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: latest
          release_name: latest
          body: ${{ steps.changelog.outputs.clean_changelog }}
