name: Automated Releases

on:
  push:
  workflow_dispatch:

jobs:
  changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      - uses: actions/checkout@v4.2.2
        name: Checkout
      - uses: actions/github-script@v7.0.1
        name: delete latest release
        env:
          GH_TOKEN: ${{ github.token }}
        with:
          github-token: ${{ github.token }}
          script: |
            await exec.exec('gh release delete latest --cleanup-tag --yes')
      - uses: actions/create-release@latest
        name: create new release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: latest
          release_name: latest
          body: update
      - uses: actions/github-script@v7.0.1
        name: workflow
        env:
          GH_TOKEN: ${{ github.token }}
        with:
          github-token: ${{ github.token }}
          script: |
            const spawn = require('child_process');
            const fs = require('node:fs');
            await spawn.execSync('gh run list --json databaseId -q "map(.databaseId)[1]" > id')
            const id = await fs.readFileSync('id').toString()
            await exec.exec(`gh run delete ${id}`)
            await exec.exec(`gh repo set-default slattman/slattman`)
            await exec.exec(`gh workflow run default.yml`)
            