name: Automated Releases

on:
  workflow_dispatch:

jobs:
  changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: TriPSs/conventional-changelog-action@latest
        name: conventional Changelog Action
        id: changelog
        with:
          github-token: ${{ github.token }}
      - uses: actions/github-script@v3
        with:
          github-token: ${{ github.token }}
          script: |
            const { owner, repo } = context.repo
            const { data: { id } } = await github.repos.getLatestRelease({ owner, repo })
            await github.repos.deleteRelease({ owner, repo, release_id: id })
      - uses: actions/create-release@latest
        name: create release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: latest
          release_name: latest
          body: ${{ steps.changelog.outputs.clean_changelog }}
